move helm template to script

diff --git a/.github/workflows/integration-test.yaml b/.github/workflows/integration-test.yaml
--- a/.github/workflows/integration-test.yaml
+++ b/.github/workflows/integration-test.yaml
@@ -27,14 +27,28 @@ jobs:
               repository: https://charts.bitnami.com/bitnami
           EOF
 
+          # Create a dummy namespace.yaml file in base
+          cat <<EOF > dev/test-chart/base/namespace.yaml
+          apiVersion: v1
+          kind: Namespace
+          metadata:
+            name: dev-namespace
+          EOF
+
           # Create a dummy kustomization.yaml file in base
           cat <<EOF > dev/test-chart/base/kustomization.yaml
-          namespace: base-namespace
+          namespace: dev-namespace
+          resources:
+            - namespace.yaml
           EOF
 
           # Create a dummy kustomization.yaml file in overlays/dev with a helmChart definition
           cat <<EOF > dev/test-chart/overlays/dev/kustomization.yaml
           namespace: dev-namespace
+          resources:
+            - ../../base
+            - ./helm-all.yaml
+
           helmCharts:
             - name: nginx
               releaseName: nginx
@@ -58,3 +72,7 @@ jobs:
             exit 1
           fi
           cat dev/test-chart/overlays/dev/all.yaml
+      - name: Validate generated files are staged
+        run: |
+            git status
+            git diff --name-only --cached | grep "dev/test-chart/overlays/dev/all.yaml" || { echo "all.yaml not found"; exit 1; }
